### PR TITLE
feat: search organization members by name or email

### LINKED ISSUE #326: [FEAT]: API Endpoint to Search for Organization Members
### Description:
Create an endpoint that allows searching for organization members by either their name or email. This will enhance the usability of our application by enabling more efficient member lookup.

### Requirements:
- [ ] Implement a POST endpoint  `/api/v1/members/search`
- [ ] Accept a JSON request body with optional name and/or email fields.
- [ ] If both parameters are provided, the endpoint should return members matching either parameter.
- [ ] Ensure the endpoint is secure and only accessible to authorized users.
- [ ] Write unit tests to cover various search scenarios.

### Request Body:
``` json
{
  "name": "optional_name",
  "email": "optional_email"
}
```

#### Success (200 OK)

 ``` json
{
    "id": "member_id",
    "name": "member_name",
    "email": "member_email",
    "status_code":  200
  }
```

### No members found (404 Not found)
``` json
{
  "error": "No members found matching the search criteria.",
  "status_code": 404
}
```

### Case: No Search Criteria Provided (400 Bad Request)
If no search criteria are provided, the request and response should be as follows:

#### Request Body:
```json
{
  "error": "At least one search criterion (name or email) must be provided.",
  "status_code": 400
}

```

 Code: `500` Internal Server Error
Response Body:
``` json
{
  "error": "Internal Server Error",
  "message": "An unexpected error occurred. Please try again later."
}
```

#### Authentication

- Verify that the user is authenticated before allowing access to the endpoint.
- Example: Use middleware to check for a valid authentication token.

#### Authorization

- Ensure that only authorized users can search for a user.
- Example: Check user roles or permissions to confirm authorization.

### Implementation Details
- Use TypeORM to interact with the PostgreSQL database.
- Perform case-insensitive searches on the name and email fields.
-  Validate the request body to ensure that at least one search criterion (name or email) is provided.
- Enhance error handling to provide more detailed error messages and HTTP status codes for different failure scenarios.

### Acceptance Criteria
- The endpoint returns a list of members matching the search criteria.
- The endpoint handles cases where no members are found.
- The endpoint is covered by unit tests demonstrating its functionality.

### PR DESCRIPTION
**Pull request by DOOMSDAY101**
# Fixes Issue/Linear Ticket

> This could be an existing issue or a linear ticket
>
> - Github Issue Example: My PR Closes #326 

## Changes proposed

Implemented a POST endpoint that allows searching for organization members by name or email. The endpoint returns organization details and member information if a match is found. Handles cases where no search criteria are provided and returns appropriate error responses.

## Check List (Check all the applicable boxes)

:rotating_light:Please review the [style guide for contributing](add link here) and [guidelines for contributing](add link here) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **main branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

### CODE REVIEW

**Review by AdeGneus — APPROVED** [review]

**Review by AdeGneus — COMMENTED** [review]
Is there no organization controller and service that you can use? Why create a new one

**Comment by DOOMSDAY101** [comment]
The new controller and service I  created was to specifically handle the search functionality for organization members by name or email.

**Comment by AdeGneus** [comment]
You don't need to create it.. that's the point

**Comment by DOOMSDAY101** [comment]
Its the same controller and service, I just made some changes to it

**Comment by DOOMSDAY101** [comment]
All changes completed.

**Review by AdeGneus — APPROVED** [review]

**Review by PreciousIfeaka — APPROVED** [review]

**Pull request merged**
